site_name: Apuntes para la certificación de Twig 3

extra_css:
    - assets/css/style.css

theme:
    favicon: assets/img/twig_logo.png
    icon:
        repo: fontawesome/brands/bitbucket
    font:
        text: Montserrat
    features:
        - navigation.instant
        - navigation.instant.progress
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    locale: es
    logo: assets/img/twig_logo.png
    palette:
        scheme: slate
        accent: green
        primary: light green

nav:
    - Basic info: index.md

markdown_extensions:
    - admonition
