site_name: Notes for Twig 3 certification

extra_css:
    - assets/css/style.css

theme:
    favicon: assets/img/twig_logo.png
    icon:
        repo: fontawesome/brands/bitbucket
    font:
        text: Montserrat
    features:
        - navigation.instant
        - navigation.instant.progress
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    locale: en
    logo: assets/img/twig_logo.png
    palette:
        scheme: slate
        accent: green
        primary: light green

markdown_extensions:
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true

nav:
    - Example tests:
          - Test 1: test/test1.md
          - Test 2: test/test2.md
          - Test 3: test/test3.md
          - Test 4: test/test4.md
          - Test 5: test/test5.md
          - Test 6: test/test6.md
          - Test 7: test/test7.md
          - Test 8: test/test8.md
          - Test 9: test/test9.md
          - Test 10: test/test10.md
    - Summary: index.md
#    - Basic Concepts:
#        - Basic Twig concepts: index.md
#        - Twig syntax: index.md
#        - Escaping: index.md
    - Filters:
        - Built-in Twig filters and their parameters: filters.md
#        - Chaining filters: index.md
#        - Alternative filter syntax: index.md
    - Tests:
        - Built-in Twig tests: tests.md
#        - Combining tests and conditional expressions: index.md
#    - Control Structures:
#        - Loops: index.md
#        - Conditionals: index.md
#        - Combining loops and conditionals: index.md
    - Variables and Expressions:
        - Defining variables: defining_variables.md
        - Accessing simple and complex variables: variables.md
        - Expressions: expressions.md
    - Functions:
        - Built-in Twig functions and their arguments: functions.md
    - Operators:
        - Built-in Twig operators: operators.md
#        - Combining operators: index.md
#    - Template Re-use:
#        - Basic and multi-level inheritance: index.md
#        - Including template fragment: index.md
#        - Embedding templates: index.md
    - Tags: tags.md
